// // Initialize the sheet - doc ID is the long id in the sheets URL
// const doc = new GoogleSpreadsheet('<the sheet ID from the url>');

// // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
// await doc.useServiceAccountAuth({
//   // env var values are copied from service account credentials generated by google
//   // see "Authentication" section in docs for more info
//   client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
//   private_key: process.env.GOOGLE_PRIVATE_KEY,
// });

// await doc.loadInfo(); // loads document properties and worksheets
// console.log(doc.title);

import { GoogleSpreadsheet } from "google-spreadsheet";
import { getToken } from "next-auth/jwt";
import type { NextApiRequest, NextApiResponse } from "next";

export default async function sheet(req: NextApiRequest, res: NextApiResponse) {
  const token = await getToken({ req });
  const doc = new GoogleSpreadsheet(
    "1vAtKUu553sw82z6a_FwXvjOcjviMCaetIYqRZzBb1NQ"
  );
  await doc.useRawAccessToken(token?.accessToken || "");

  await doc.loadInfo(); // loads document properties and worksheets
  // console.log(doc.title);
  res.send({
    title: doc.title,
  });
}
